define(["require", "exports", "./BoxGeometry.js", "./BoxBufferGeometry.js", "./CircleGeometry.js", "./CircleBufferGeometry.js", "./ConeGeometry.js", "./ConeBufferGeometry.js", "./CylinderGeometry.js", "./CylinderBufferGeometry.js", "./DodecahedronGeometry.js", "./DodecahedronBufferGeometry.js", "./EdgesGeometry.js", "./ExtrudeGeometry.js", "./ExtrudeBufferGeometry.js", "./IcosahedronGeometry.js", "./IcosahedronBufferGeometry.js", "./LatheGeometry.js", "./LatheBufferGeometry.js", "./OctahedronGeometry.js", "./OctahedronBufferGeometry.js", "./ParametricGeometry.js", "./ParametricBufferGeometry.js", "./PlaneGeometry.js", "./PlaneBufferGeometry.js", "./PolyhedronGeometry.js", "./PolyhedronBufferGeometry.js", "./RingGeometry.js", "./RingBufferGeometry.js", "./ShapeGeometry.js", "./ShapeBufferGeometry.js", "./SphereGeometry.js", "./SphereBufferGeometry.js", "./TetrahedronGeometry.js", "./TetrahedronBufferGeometry.js", "./TextGeometry.js", "./TextBufferGeometry.js", "./TorusGeometry.js", "./TorusBufferGeometry.js", "./TorusKnotGeometry.js", "./TorusKnotBufferGeometry.js", "./TubeGeometry.js", "./TubeBufferGeometry.js", "./WireframeGeometry.js"], function (require, exports, BoxGeometry_js_1, BoxBufferGeometry_js_1, CircleGeometry_js_1, CircleBufferGeometry_js_1, ConeGeometry_js_1, ConeBufferGeometry_js_1, CylinderGeometry_js_1, CylinderBufferGeometry_js_1, DodecahedronGeometry_js_1, DodecahedronBufferGeometry_js_1, EdgesGeometry_js_1, ExtrudeGeometry_js_1, ExtrudeBufferGeometry_js_1, IcosahedronGeometry_js_1, IcosahedronBufferGeometry_js_1, LatheGeometry_js_1, LatheBufferGeometry_js_1, OctahedronGeometry_js_1, OctahedronBufferGeometry_js_1, ParametricGeometry_js_1, ParametricBufferGeometry_js_1, PlaneGeometry_js_1, PlaneBufferGeometry_js_1, PolyhedronGeometry_js_1, PolyhedronBufferGeometry_js_1, RingGeometry_js_1, RingBufferGeometry_js_1, ShapeGeometry_js_1, ShapeBufferGeometry_js_1, SphereGeometry_js_1, SphereBufferGeometry_js_1, TetrahedronGeometry_js_1, TetrahedronBufferGeometry_js_1, TextGeometry_js_1, TextBufferGeometry_js_1, TorusGeometry_js_1, TorusBufferGeometry_js_1, TorusKnotGeometry_js_1, TorusKnotBufferGeometry_js_1, TubeGeometry_js_1, TubeBufferGeometry_js_1, WireframeGeometry_js_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.BoxGeometry = BoxGeometry_js_1.BoxGeometry;
    exports.BoxBufferGeometry = BoxBufferGeometry_js_1.BoxBufferGeometry;
    exports.CircleGeometry = CircleGeometry_js_1.CircleGeometry;
    exports.CircleBufferGeometry = CircleBufferGeometry_js_1.CircleBufferGeometry;
    exports.ConeGeometry = ConeGeometry_js_1.ConeGeometry;
    exports.ConeBufferGeometry = ConeBufferGeometry_js_1.ConeBufferGeometry;
    exports.CylinderGeometry = CylinderGeometry_js_1.CylinderGeometry;
    exports.CylinderBufferGeometry = CylinderBufferGeometry_js_1.CylinderBufferGeometry;
    exports.DodecahedronGeometry = DodecahedronGeometry_js_1.DodecahedronGeometry;
    exports.DodecahedronBufferGeometry = DodecahedronBufferGeometry_js_1.DodecahedronBufferGeometry;
    exports.EdgesGeometry = EdgesGeometry_js_1.EdgesGeometry;
    exports.ExtrudeGeometry = ExtrudeGeometry_js_1.ExtrudeGeometry;
    exports.ExtrudeBufferGeometry = ExtrudeBufferGeometry_js_1.ExtrudeBufferGeometry;
    exports.IcosahedronGeometry = IcosahedronGeometry_js_1.IcosahedronGeometry;
    exports.IcosahedronBufferGeometry = IcosahedronBufferGeometry_js_1.IcosahedronBufferGeometry;
    exports.LatheGeometry = LatheGeometry_js_1.LatheGeometry;
    exports.LatheBufferGeometry = LatheBufferGeometry_js_1.LatheBufferGeometry;
    exports.OctahedronGeometry = OctahedronGeometry_js_1.OctahedronGeometry;
    exports.OctahedronBufferGeometry = OctahedronBufferGeometry_js_1.OctahedronBufferGeometry;
    exports.ParametricGeometry = ParametricGeometry_js_1.ParametricGeometry;
    exports.ParametricBufferGeometry = ParametricBufferGeometry_js_1.ParametricBufferGeometry;
    exports.PlaneGeometry = PlaneGeometry_js_1.PlaneGeometry;
    exports.PlaneBufferGeometry = PlaneBufferGeometry_js_1.PlaneBufferGeometry;
    exports.PolyhedronGeometry = PolyhedronGeometry_js_1.PolyhedronGeometry;
    exports.PolyhedronBufferGeometry = PolyhedronBufferGeometry_js_1.PolyhedronBufferGeometry;
    exports.RingGeometry = RingGeometry_js_1.RingGeometry;
    exports.RingBufferGeometry = RingBufferGeometry_js_1.RingBufferGeometry;
    exports.ShapeGeometry = ShapeGeometry_js_1.ShapeGeometry;
    exports.ShapeBufferGeometry = ShapeBufferGeometry_js_1.ShapeBufferGeometry;
    exports.SphereGeometry = SphereGeometry_js_1.SphereGeometry;
    exports.SphereBufferGeometry = SphereBufferGeometry_js_1.SphereBufferGeometry;
    exports.TetrahedronGeometry = TetrahedronGeometry_js_1.TetrahedronGeometry;
    exports.TetrahedronBufferGeometry = TetrahedronBufferGeometry_js_1.TetrahedronBufferGeometry;
    exports.TextGeometry = TextGeometry_js_1.TextGeometry;
    exports.TextBufferGeometry = TextBufferGeometry_js_1.TextBufferGeometry;
    exports.TorusGeometry = TorusGeometry_js_1.TorusGeometry;
    exports.TorusBufferGeometry = TorusBufferGeometry_js_1.TorusBufferGeometry;
    exports.TorusKnotGeometry = TorusKnotGeometry_js_1.TorusKnotGeometry;
    exports.TorusKnotBufferGeometry = TorusKnotBufferGeometry_js_1.TorusKnotBufferGeometry;
    exports.TubeGeometry = TubeGeometry_js_1.TubeGeometry;
    exports.TubeBufferGeometry = TubeBufferGeometry_js_1.TubeBufferGeometry;
    exports.WireframeGeometry = WireframeGeometry_js_1.WireframeGeometry;
});
//# sourceMappingURL=Geometries.js.map