define(["require", "exports", "./constants.js", "./renderers/WebGLMultisampleRenderTarget.js", "./renderers/WebGLCubeRenderTarget.js", "./renderers/WebGLRenderTarget.js", "./renderers/WebGLRenderer.js", "./renderers/WebGL1Renderer.js", "./renderers/shaders/ShaderLib.js", "./renderers/shaders/UniformsLib.js", "./renderers/shaders/UniformsUtils.js", "./renderers/shaders/ShaderChunk.js", "./scenes/FogExp2.js", "./scenes/Fog.js", "./scenes/Scene.js", "./objects/Sprite.js", "./objects/LOD.js", "./objects/SkinnedMesh.js", "./objects/Skeleton.js", "./objects/Bone.js", "./objects/Mesh.js", "./objects/InstancedMesh.js", "./objects/LineSegments.js", "./objects/LineLoop.js", "./objects/Line.js", "./objects/Points.js", "./objects/Group.js", "./textures/VideoTexture.js", "./textures/DataTexture.js", "./textures/DataTexture2DArray.js", "./textures/DataTexture3D.js", "./textures/CompressedTexture.js", "./textures/CubeTexture.js", "./textures/CanvasTexture.js", "./textures/DepthTexture.js", "./textures/Texture.js", "./geometries/Geometries.js", "./materials/Materials.js", "./loaders/AnimationLoader.js", "./loaders/CompressedTextureLoader.js", "./loaders/CubeTextureLoader.js", "./loaders/DataTextureLoader.js", "./loaders/TextureLoader.js", "./loaders/ObjectLoader.js", "./loaders/MaterialLoader.js", "./loaders/BufferGeometryLoader.js", "./loaders/LoadingManager.js", "./loaders/ImageLoader.js", "./loaders/ImageBitmapLoader.js", "./loaders/FontLoader.js", "./loaders/FileLoader.js", "./loaders/Loader.js", "./loaders/LoaderUtils.js", "./loaders/Cache.js", "./loaders/AudioLoader.js", "./lights/SpotLight.js", "./lights/PointLight.js", "./lights/RectAreaLight.js", "./lights/HemisphereLight.js", "./lights/HemisphereLightProbe.js", "./lights/DirectionalLight.js", "./lights/AmbientLight.js", "./lights/AmbientLightProbe.js", "./lights/Light.js", "./lights/LightProbe.js", "./cameras/StereoCamera.js", "./cameras/PerspectiveCamera.js", "./cameras/OrthographicCamera.js", "./cameras/CubeCamera.js", "./cameras/ArrayCamera.js", "./cameras/Camera.js", "./audio/AudioListener.js", "./audio/PositionalAudio.js", "./audio/AudioContext.js", "./audio/AudioAnalyser.js", "./audio/Audio.js", "./animation/tracks/VectorKeyframeTrack.js", "./animation/tracks/StringKeyframeTrack.js", "./animation/tracks/QuaternionKeyframeTrack.js", "./animation/tracks/NumberKeyframeTrack.js", "./animation/tracks/ColorKeyframeTrack.js", "./animation/tracks/BooleanKeyframeTrack.js", "./animation/PropertyMixer.js", "./animation/PropertyBinding.js", "./animation/KeyframeTrack.js", "./animation/AnimationUtils.js", "./animation/AnimationObjectGroup.js", "./animation/AnimationMixer.js", "./animation/AnimationClip.js", "./core/Uniform.js", "./core/InstancedBufferGeometry.js", "./core/BufferGeometry.js", "./core/Geometry.js", "./core/InterleavedBufferAttribute.js", "./core/InstancedInterleavedBuffer.js", "./core/InterleavedBuffer.js", "./core/InstancedBufferAttribute.js", "./core/GLBufferAttribute.js", "./core/BufferAttribute.js", "./core/Face3.js", "./core/Object3D.js", "./core/Raycaster.js", "./core/Layers.js", "./core/EventDispatcher.js", "./core/Clock.js", "./math/interpolants/QuaternionLinearInterpolant.js", "./math/interpolants/LinearInterpolant.js", "./math/interpolants/DiscreteInterpolant.js", "./math/interpolants/CubicInterpolant.js", "./math/Interpolant.js", "./math/Triangle.js", "./math/MathUtils.js", "./math/Spherical.js", "./math/Cylindrical.js", "./math/Plane.js", "./math/Frustum.js", "./math/Sphere.js", "./math/Ray.js", "./math/Matrix4.js", "./math/Matrix3.js", "./math/Box3.js", "./math/Box2.js", "./math/Line3.js", "./math/Euler.js", "./math/Vector4.js", "./math/Vector3.js", "./math/Vector2.js", "./math/Quaternion.js", "./math/Color.js", "./math/SphericalHarmonics3.js", "./extras/objects/ImmediateRenderObject.js", "./helpers/SpotLightHelper.js", "./helpers/SkeletonHelper.js", "./helpers/PointLightHelper.js", "./helpers/HemisphereLightHelper.js", "./helpers/GridHelper.js", "./helpers/PolarGridHelper.js", "./helpers/DirectionalLightHelper.js", "./helpers/CameraHelper.js", "./helpers/BoxHelper.js", "./helpers/Box3Helper.js", "./helpers/PlaneHelper.js", "./helpers/ArrowHelper.js", "./helpers/AxesHelper.js", "./extras/curves/Curves.js", "./extras/core/Shape.js", "./extras/core/Path.js", "./extras/core/ShapePath.js", "./extras/core/Font.js", "./extras/core/CurvePath.js", "./extras/core/Curve.js", "./extras/ImageUtils.js", "./extras/ShapeUtils.js", "./extras/PMREMGenerator.js", "./renderers/webgl/WebGLUtils.js", "./constants.js", "./Three.Legacy.js"], function (require, exports, constants_js_1, WebGLMultisampleRenderTarget_js_1, WebGLCubeRenderTarget_js_1, WebGLRenderTarget_js_1, WebGLRenderer_js_1, WebGL1Renderer_js_1, ShaderLib_js_1, UniformsLib_js_1, UniformsUtils_js_1, ShaderChunk_js_1, FogExp2_js_1, Fog_js_1, Scene_js_1, Sprite_js_1, LOD_js_1, SkinnedMesh_js_1, Skeleton_js_1, Bone_js_1, Mesh_js_1, InstancedMesh_js_1, LineSegments_js_1, LineLoop_js_1, Line_js_1, Points_js_1, Group_js_1, VideoTexture_js_1, DataTexture_js_1, DataTexture2DArray_js_1, DataTexture3D_js_1, CompressedTexture_js_1, CubeTexture_js_1, CanvasTexture_js_1, DepthTexture_js_1, Texture_js_1, Geometries_js_1, Materials_js_1, AnimationLoader_js_1, CompressedTextureLoader_js_1, CubeTextureLoader_js_1, DataTextureLoader_js_1, TextureLoader_js_1, ObjectLoader_js_1, MaterialLoader_js_1, BufferGeometryLoader_js_1, LoadingManager_js_1, ImageLoader_js_1, ImageBitmapLoader_js_1, FontLoader_js_1, FileLoader_js_1, Loader_js_1, LoaderUtils_js_1, Cache_js_1, AudioLoader_js_1, SpotLight_js_1, PointLight_js_1, RectAreaLight_js_1, HemisphereLight_js_1, HemisphereLightProbe_js_1, DirectionalLight_js_1, AmbientLight_js_1, AmbientLightProbe_js_1, Light_js_1, LightProbe_js_1, StereoCamera_js_1, PerspectiveCamera_js_1, OrthographicCamera_js_1, CubeCamera_js_1, ArrayCamera_js_1, Camera_js_1, AudioListener_js_1, PositionalAudio_js_1, AudioContext_js_1, AudioAnalyser_js_1, Audio_js_1, VectorKeyframeTrack_js_1, StringKeyframeTrack_js_1, QuaternionKeyframeTrack_js_1, NumberKeyframeTrack_js_1, ColorKeyframeTrack_js_1, BooleanKeyframeTrack_js_1, PropertyMixer_js_1, PropertyBinding_js_1, KeyframeTrack_js_1, AnimationUtils_js_1, AnimationObjectGroup_js_1, AnimationMixer_js_1, AnimationClip_js_1, Uniform_js_1, InstancedBufferGeometry_js_1, BufferGeometry_js_1, Geometry_js_1, InterleavedBufferAttribute_js_1, InstancedInterleavedBuffer_js_1, InterleavedBuffer_js_1, InstancedBufferAttribute_js_1, GLBufferAttribute_js_1, BufferAttribute_js_1, Face3_js_1, Object3D_js_1, Raycaster_js_1, Layers_js_1, EventDispatcher_js_1, Clock_js_1, QuaternionLinearInterpolant_js_1, LinearInterpolant_js_1, DiscreteInterpolant_js_1, CubicInterpolant_js_1, Interpolant_js_1, Triangle_js_1, MathUtils_js_1, Spherical_js_1, Cylindrical_js_1, Plane_js_1, Frustum_js_1, Sphere_js_1, Ray_js_1, Matrix4_js_1, Matrix3_js_1, Box3_js_1, Box2_js_1, Line3_js_1, Euler_js_1, Vector4_js_1, Vector3_js_1, Vector2_js_1, Quaternion_js_1, Color_js_1, SphericalHarmonics3_js_1, ImmediateRenderObject_js_1, SpotLightHelper_js_1, SkeletonHelper_js_1, PointLightHelper_js_1, HemisphereLightHelper_js_1, GridHelper_js_1, PolarGridHelper_js_1, DirectionalLightHelper_js_1, CameraHelper_js_1, BoxHelper_js_1, Box3Helper_js_1, PlaneHelper_js_1, ArrowHelper_js_1, AxesHelper_js_1, Curves_js_1, Shape_js_1, Path_js_1, ShapePath_js_1, Font_js_1, CurvePath_js_1, Curve_js_1, ImageUtils_js_1, ShapeUtils_js_1, PMREMGenerator_js_1, WebGLUtils_js_1, constants_js_2, Three_Legacy_js_1) {
    "use strict";
    function __export(m) {
        for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
    }
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.WebGLMultisampleRenderTarget = WebGLMultisampleRenderTarget_js_1.WebGLMultisampleRenderTarget;
    exports.WebGLCubeRenderTarget = WebGLCubeRenderTarget_js_1.WebGLCubeRenderTarget;
    exports.WebGLRenderTarget = WebGLRenderTarget_js_1.WebGLRenderTarget;
    exports.WebGLRenderer = WebGLRenderer_js_1.WebGLRenderer;
    exports.WebGL1Renderer = WebGL1Renderer_js_1.WebGL1Renderer;
    exports.ShaderLib = ShaderLib_js_1.ShaderLib;
    exports.UniformsLib = UniformsLib_js_1.UniformsLib;
    exports.UniformsUtils = UniformsUtils_js_1.UniformsUtils;
    exports.ShaderChunk = ShaderChunk_js_1.ShaderChunk;
    exports.FogExp2 = FogExp2_js_1.FogExp2;
    exports.Fog = Fog_js_1.Fog;
    exports.Scene = Scene_js_1.Scene;
    exports.Sprite = Sprite_js_1.Sprite;
    exports.LOD = LOD_js_1.LOD;
    exports.SkinnedMesh = SkinnedMesh_js_1.SkinnedMesh;
    exports.Skeleton = Skeleton_js_1.Skeleton;
    exports.Bone = Bone_js_1.Bone;
    exports.Mesh = Mesh_js_1.Mesh;
    exports.InstancedMesh = InstancedMesh_js_1.InstancedMesh;
    exports.LineSegments = LineSegments_js_1.LineSegments;
    exports.LineLoop = LineLoop_js_1.LineLoop;
    exports.Line = Line_js_1.Line;
    exports.Points = Points_js_1.Points;
    exports.Group = Group_js_1.Group;
    exports.VideoTexture = VideoTexture_js_1.VideoTexture;
    exports.DataTexture = DataTexture_js_1.DataTexture;
    exports.DataTexture2DArray = DataTexture2DArray_js_1.DataTexture2DArray;
    exports.DataTexture3D = DataTexture3D_js_1.DataTexture3D;
    exports.CompressedTexture = CompressedTexture_js_1.CompressedTexture;
    exports.CubeTexture = CubeTexture_js_1.CubeTexture;
    exports.CanvasTexture = CanvasTexture_js_1.CanvasTexture;
    exports.DepthTexture = DepthTexture_js_1.DepthTexture;
    exports.Texture = Texture_js_1.Texture;
    __export(Geometries_js_1);
    __export(Materials_js_1);
    exports.AnimationLoader = AnimationLoader_js_1.AnimationLoader;
    exports.CompressedTextureLoader = CompressedTextureLoader_js_1.CompressedTextureLoader;
    exports.CubeTextureLoader = CubeTextureLoader_js_1.CubeTextureLoader;
    exports.DataTextureLoader = DataTextureLoader_js_1.DataTextureLoader;
    exports.TextureLoader = TextureLoader_js_1.TextureLoader;
    exports.ObjectLoader = ObjectLoader_js_1.ObjectLoader;
    exports.MaterialLoader = MaterialLoader_js_1.MaterialLoader;
    exports.BufferGeometryLoader = BufferGeometryLoader_js_1.BufferGeometryLoader;
    exports.DefaultLoadingManager = LoadingManager_js_1.DefaultLoadingManager;
    exports.LoadingManager = LoadingManager_js_1.LoadingManager;
    exports.ImageLoader = ImageLoader_js_1.ImageLoader;
    exports.ImageBitmapLoader = ImageBitmapLoader_js_1.ImageBitmapLoader;
    exports.FontLoader = FontLoader_js_1.FontLoader;
    exports.FileLoader = FileLoader_js_1.FileLoader;
    exports.Loader = Loader_js_1.Loader;
    exports.LoaderUtils = LoaderUtils_js_1.LoaderUtils;
    exports.Cache = Cache_js_1.Cache;
    exports.AudioLoader = AudioLoader_js_1.AudioLoader;
    exports.SpotLight = SpotLight_js_1.SpotLight;
    exports.PointLight = PointLight_js_1.PointLight;
    exports.RectAreaLight = RectAreaLight_js_1.RectAreaLight;
    exports.HemisphereLight = HemisphereLight_js_1.HemisphereLight;
    exports.HemisphereLightProbe = HemisphereLightProbe_js_1.HemisphereLightProbe;
    exports.DirectionalLight = DirectionalLight_js_1.DirectionalLight;
    exports.AmbientLight = AmbientLight_js_1.AmbientLight;
    exports.AmbientLightProbe = AmbientLightProbe_js_1.AmbientLightProbe;
    exports.Light = Light_js_1.Light;
    exports.LightProbe = LightProbe_js_1.LightProbe;
    exports.StereoCamera = StereoCamera_js_1.StereoCamera;
    exports.PerspectiveCamera = PerspectiveCamera_js_1.PerspectiveCamera;
    exports.OrthographicCamera = OrthographicCamera_js_1.OrthographicCamera;
    exports.CubeCamera = CubeCamera_js_1.CubeCamera;
    exports.ArrayCamera = ArrayCamera_js_1.ArrayCamera;
    exports.Camera = Camera_js_1.Camera;
    exports.AudioListener = AudioListener_js_1.AudioListener;
    exports.PositionalAudio = PositionalAudio_js_1.PositionalAudio;
    exports.AudioContext = AudioContext_js_1.AudioContext;
    exports.AudioAnalyser = AudioAnalyser_js_1.AudioAnalyser;
    exports.Audio = Audio_js_1.Audio;
    exports.VectorKeyframeTrack = VectorKeyframeTrack_js_1.VectorKeyframeTrack;
    exports.StringKeyframeTrack = StringKeyframeTrack_js_1.StringKeyframeTrack;
    exports.QuaternionKeyframeTrack = QuaternionKeyframeTrack_js_1.QuaternionKeyframeTrack;
    exports.NumberKeyframeTrack = NumberKeyframeTrack_js_1.NumberKeyframeTrack;
    exports.ColorKeyframeTrack = ColorKeyframeTrack_js_1.ColorKeyframeTrack;
    exports.BooleanKeyframeTrack = BooleanKeyframeTrack_js_1.BooleanKeyframeTrack;
    exports.PropertyMixer = PropertyMixer_js_1.PropertyMixer;
    exports.PropertyBinding = PropertyBinding_js_1.PropertyBinding;
    exports.KeyframeTrack = KeyframeTrack_js_1.KeyframeTrack;
    exports.AnimationUtils = AnimationUtils_js_1.AnimationUtils;
    exports.AnimationObjectGroup = AnimationObjectGroup_js_1.AnimationObjectGroup;
    exports.AnimationMixer = AnimationMixer_js_1.AnimationMixer;
    exports.AnimationClip = AnimationClip_js_1.AnimationClip;
    exports.Uniform = Uniform_js_1.Uniform;
    exports.InstancedBufferGeometry = InstancedBufferGeometry_js_1.InstancedBufferGeometry;
    exports.BufferGeometry = BufferGeometry_js_1.BufferGeometry;
    exports.Geometry = Geometry_js_1.Geometry;
    exports.InterleavedBufferAttribute = InterleavedBufferAttribute_js_1.InterleavedBufferAttribute;
    exports.InstancedInterleavedBuffer = InstancedInterleavedBuffer_js_1.InstancedInterleavedBuffer;
    exports.InterleavedBuffer = InterleavedBuffer_js_1.InterleavedBuffer;
    exports.InstancedBufferAttribute = InstancedBufferAttribute_js_1.InstancedBufferAttribute;
    exports.GLBufferAttribute = GLBufferAttribute_js_1.GLBufferAttribute;
    __export(BufferAttribute_js_1);
    exports.Face3 = Face3_js_1.Face3;
    exports.Object3D = Object3D_js_1.Object3D;
    exports.Raycaster = Raycaster_js_1.Raycaster;
    exports.Layers = Layers_js_1.Layers;
    exports.EventDispatcher = EventDispatcher_js_1.EventDispatcher;
    exports.Clock = Clock_js_1.Clock;
    exports.QuaternionLinearInterpolant = QuaternionLinearInterpolant_js_1.QuaternionLinearInterpolant;
    exports.LinearInterpolant = LinearInterpolant_js_1.LinearInterpolant;
    exports.DiscreteInterpolant = DiscreteInterpolant_js_1.DiscreteInterpolant;
    exports.CubicInterpolant = CubicInterpolant_js_1.CubicInterpolant;
    exports.Interpolant = Interpolant_js_1.Interpolant;
    exports.Triangle = Triangle_js_1.Triangle;
    exports.MathUtils = MathUtils_js_1.MathUtils;
    exports.Spherical = Spherical_js_1.Spherical;
    exports.Cylindrical = Cylindrical_js_1.Cylindrical;
    exports.Plane = Plane_js_1.Plane;
    exports.Frustum = Frustum_js_1.Frustum;
    exports.Sphere = Sphere_js_1.Sphere;
    exports.Ray = Ray_js_1.Ray;
    exports.Matrix4 = Matrix4_js_1.Matrix4;
    exports.Matrix3 = Matrix3_js_1.Matrix3;
    exports.Box3 = Box3_js_1.Box3;
    exports.Box2 = Box2_js_1.Box2;
    exports.Line3 = Line3_js_1.Line3;
    exports.Euler = Euler_js_1.Euler;
    exports.Vector4 = Vector4_js_1.Vector4;
    exports.Vector3 = Vector3_js_1.Vector3;
    exports.Vector2 = Vector2_js_1.Vector2;
    exports.Quaternion = Quaternion_js_1.Quaternion;
    exports.Color = Color_js_1.Color;
    exports.SphericalHarmonics3 = SphericalHarmonics3_js_1.SphericalHarmonics3;
    exports.ImmediateRenderObject = ImmediateRenderObject_js_1.ImmediateRenderObject;
    exports.SpotLightHelper = SpotLightHelper_js_1.SpotLightHelper;
    exports.SkeletonHelper = SkeletonHelper_js_1.SkeletonHelper;
    exports.PointLightHelper = PointLightHelper_js_1.PointLightHelper;
    exports.HemisphereLightHelper = HemisphereLightHelper_js_1.HemisphereLightHelper;
    exports.GridHelper = GridHelper_js_1.GridHelper;
    exports.PolarGridHelper = PolarGridHelper_js_1.PolarGridHelper;
    exports.DirectionalLightHelper = DirectionalLightHelper_js_1.DirectionalLightHelper;
    exports.CameraHelper = CameraHelper_js_1.CameraHelper;
    exports.BoxHelper = BoxHelper_js_1.BoxHelper;
    exports.Box3Helper = Box3Helper_js_1.Box3Helper;
    exports.PlaneHelper = PlaneHelper_js_1.PlaneHelper;
    exports.ArrowHelper = ArrowHelper_js_1.ArrowHelper;
    exports.AxesHelper = AxesHelper_js_1.AxesHelper;
    __export(Curves_js_1);
    exports.Shape = Shape_js_1.Shape;
    exports.Path = Path_js_1.Path;
    exports.ShapePath = ShapePath_js_1.ShapePath;
    exports.Font = Font_js_1.Font;
    exports.CurvePath = CurvePath_js_1.CurvePath;
    exports.Curve = Curve_js_1.Curve;
    exports.ImageUtils = ImageUtils_js_1.ImageUtils;
    exports.ShapeUtils = ShapeUtils_js_1.ShapeUtils;
    exports.PMREMGenerator = PMREMGenerator_js_1.PMREMGenerator;
    exports.WebGLUtils = WebGLUtils_js_1.WebGLUtils;
    __export(constants_js_2);
    __export(Three_Legacy_js_1);
    if (typeof __THREE_DEVTOOLS__ !== 'undefined') {
        /* eslint-disable no-undef */
        __THREE_DEVTOOLS__.dispatchEvent(new CustomEvent('register', { detail: {
                revision: constants_js_1.REVISION,
            } }));
        /* eslint-enable no-undef */
    }
});
//# sourceMappingURL=Three.js.map